export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE';
export const SELECCIONAR_ALIMENTO = 'SELECCIONAR_ALIMENTO';
export const CANTIDAD_ALIMENTO = 'CANTIDAD_ALIMENTO';
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL';